tas 4 and task 4
js-tasks-ru/js-20220418_larysa-skrypkin pull request #3
Opened 2022-04-28 19:37 UTC by Skrypkina

2022-04-28 19:38 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-29 13:09 UTC, dragozin requested changes
Реализацию функции createGetter необходимо доработать.

2022-04-29 13:09 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      return obj[values[0]][values[1]];
привет! массив values может быть любого допустимого размера. т.е. больше четырех.
Подумайте, пожалуйста, как эту задачку можно решить.
Как подсказка: помните, что объекты передаются по ссылке и например `obj[values[0]][values[1]]` можно хранить в переменной и итеративно изменять это значение.

2022-05-02 12:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dragozin

2022-05-02 14:41 UTC, dragozin requested changes
Есть небольшая ошибка в createGetter

Если есть возможность, то лучше решение доработать.

2022-05-02 14:41 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (JSON.stringify(object) === '{}') {
Можно не обрабатывать случай с пустым объектом. Object.entries для пустого объекта вернет пустой массив, т.е. алгоритм ниже справится с пустым объектом.

2022-05-02 14:41 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      obj = obj[val];
Принцип для решения выбран правильно. Но необходимо обработать случай, когда в строке существуют свойства, которые отсутствуют в объекте.  Сейчас в таком случае будет ошибка. Например,

```
const getter = createGetter('test.test')
const obj = {test: null}
getter(obj)
```

2022-05-02 14:41 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +    const num = arr.length >= size ? length : 0;
Похоже Вы хотите обработать отрицательное значение length

можно это сделать так:
```
const num = Math.max(arr.length - size,0)
```

2022-05-02 17:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dragozin

2022-05-02 21:08 UTC, dragozin approved these changes

2022-05-02 21:08 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (obj[val] === null) {
помимо null в значении `obj[val]` может быть так же undefined

Для того, чтобы обработать сразу оба этих кейса и не делать еще одну проверку подойдет проверка значения в условии

```
if (!obj[val]) {
   return
}
```

Это будет работать т.к. и `null` и `undefined` будут давать false в логическом контексте.


Если будет желание - можно это доработать в отдельном PR, этот результат я принимаю.

2022-05-02 21:09 UTC, merged