task 4
js-tasks-ru/js-20220418_larysa-skrypkin pull request #4
Opened 2022-05-08 21:31 UTC by Skrypkina

2022-05-08 21:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-08 22:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-09 10:10 UTC, dragozin requested changes

2022-05-09 10:10 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    // columnChart.destroy();
метод destroy необходимо реализовать на компоненте 

Метод destroy - чистит все что создал компонент (элементы, отписывается от событий если есть подписки). Например, если мы переходим между страницами нашего приложения, компоненты предыдущей страницы больше не нужны и их нужно удалить, чтобы не было утечек памяти.

Так же необходимо реализовать метод remove
Метод remove отвечает за удаление элемента со страницы (из DOM). Например, если у нас есть компонент tooltip - он появляется в DOM для отображения подсказки и если не нужен - удаляется.

2022-05-09 10:10 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +const noop = () => {};
в данном конкретном случае подойдет функция которая просто возвращает переданное значение

```
const defaultFormatHeading = value => value;
```
Иначе если функция не передана, то значение не отобразится вообще.

`noop` пригодится потом, когда будем получать коллбеки как параметры при обработке событий

2022-05-09 10:10 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   const number = this.label === 'sales' ? `${this.formatHeading(this.value)}` : `${this.value}`;
компонент - это универсальный строительный блок. Label - может быть любой строкой, если вы будете завязываться на конкретные значения label - то универсальность пропадает. 
formatHeading нужен для того, чтобы как раз обеспечить эту универсальность. Потребитель может передать любую функцию для форматирования - можно форматировать в нужную локаль, в разные языки, системы счисления и т.д. В вашей реализации происходит завязка на данные и универсальность теряется. 

как совет - сохранить в formatHeading по умолчанию функцию, которая просто возвращает переданное значение `const defaultFormatHeading = value => value;`

2022-05-09 10:10 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   this.render();
как я уже говорил, функцию render при update вызывать не эффективно, а в данном случае не корректно.
достаточно заново отрисовать только графики
т.е. элемент:
```
div data-element="body" class="column-chart__chart"
```
Подумайте, пожалуйста, как можно получить этот элемент, мы это проходили на лекции. Так же постарайтесь, пожалуйста, изучить доп. материалы после лекции - они могут дать дополнительные ответы на возникшие вопросы.


в вашем случае update не сработает и новые данные не отобразятся на странице, т.к. нужно еще дополнительно удалить элемент из DOM и добавить новый элемент.

2022-05-09 10:10 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    const formatHeading = data => `$${data}`;
Тест необходимо вернуть - он как раз проверяет, что можно форматировать заголовок универсальным способом.

2022-05-09 12:41 UTC, Skrypkina commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    // columnChart.destroy();
это как раз и причина, почему все 10 тестов падают. 
![Screenshot 2022-05-09 at 15 40 04](https://user-images.githubusercontent.com/35501870/167411901-bd8152b8-9ff5-46a4-96d6-42c60e943599.png)

2022-05-09 12:42 UTC, Skrypkina commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   const number = this.label === 'sales' ? `${this.formatHeading(this.value)}` : `${this.value}`;
+

2022-05-09 12:44 UTC, Skrypkina commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    // columnChart.destroy();
когда я его комментирую и еще этот // it('should have ability to be removed', () => {
  //   columnChart.remove();

  //   expect(columnChart.element).not.toBeInTheDocument();
  // }); - тогда все нормально

2022-05-09 13:17 UTC, Skrypkina commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    const formatHeading = data => `$${data}`;
Тут ведь только число передается, а знак добавляет уже функция. Просто в тестах функция добавляет USD, а в коде знак доллара. Функции разные. Или нужно в функцию еще и символ передавать? Тут непонятно

2022-05-09 16:20 UTC, Skrypkina commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   this.render();
Пробовала достучаться методом document.querySelector, но приходит ноль. Я погуглила - это не загрузился html и еще нет обьекта, хотя обьект на странице есть. Тут нужна ваша помощь

2022-05-09 17:11 UTC, dragozin approved these changes

2022-05-09 17:11 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    // columnChart.destroy();
> метод destroy необходимо реализовать на компоненте

Тест падает, т.к. у вас нет этого метода. Вам его нужно реализовать

2022-05-09 17:11 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   this.render();
Напомню, мы на лекции проходили, что, метод `querySelector` существует не только у объекта document, так же у элементов DOM. 

например, вы можете выполнить так: 
```
this.element.querySelector
```

2022-05-09 17:11 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   const number = this.label === 'sales' ? `${this.formatHeading(this.value)}` : `${this.value}`;
изменений нет, возможно забыли залить?

2022-05-09 17:11 UTC, dragozin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.spec.js
> +    const formatHeading = data => `$${data}`;
Ваш компонент должен просто вызвать эту функцию и передать в нее value и отрисовать то, что вернет функция. Т.е. можно сделать так:


```
constructor({ data = [], label = '', value = null, link = '', formatHeading = value=>value} = {}) {
   this.data = data;
   this.label = label;
   this.value = formatHeading(value);
   this.link = link;
   this.render();
 }
```

2022-05-09 17:12 UTC, merged

2022-05-09 17:12 UTC, dragozin commented
случайно нажал approve